// react/my-pain/test-app/src/App.js
import './App.css';
import { useState, useEffect, useCallback } from 'react'
import axios from 'axios'
import TaskForm from './Components/TaskForm';

function App() {

  const [error, setError] = useState(null);
  const [tasks, setTasks] = useState([]);

  useEffect(() => {
    axios.get("http://185.246.66.84:3000/etorbunova/tasks")
    .then(res => setTasks(res.data))
    .catch(err => setError(err))
  },[])

  function calcSequence(){
    return tasks.length + 2;
  }

  const CreateTask = useCallback(() => {
    
    const newTask = {
        completed: false,
        title: tasks.length === 0 ? "Task 1" : "Task " + (tasks.length + 1),
        sequence: calcSequence()
    }
    axios.post("http://185.246.66.84:3000/etorbunova/tasks", newTask)
    .then(response => {
        setTasks(prev =>
            [...prev,response.data]
        );
    })
    .catch(error => console.log(error));
  },[tasks, setTasks]) 
  
  function deleteTask(id){
    axios.delete("http://185.246.66.84:3000/etorbunova/tasks/" + id)
      .then(response => {
          setTasks(prev => prev.filter(curr => curr.id !== id)
          );
      })
      .catch(error => console.log(error));
  }  

  /*const deleteTask = useCallback((id) => {
      axios.delete("http://185.246.66.84:3000/etorbunova/tasks/" + id)
      .then(response => {
          setTasks(prev => prev.filter(curr => curr.id !== id)
          );
      })
      .catch(error => console.log(error));
  },[setTasks])  */
  

  const checkboxDone = useCallback((task) => {
      axios.put("http://185.246.66.84:3000/etorbunova/tasks/" + task.id, {
          completed: !task.completed,
          title: task.title,
          sequence: task.sequence           
      })
      .then(response => {
          setTasks(prev =>{
              return [...prev.filter(curr => curr.id !== task.id),response.data]
          });
      })
      .catch(error => console.log(error));
  },[setTasks])
  
  
  const renameTask = useCallback((task, newTitle) => {
      console.log("http://185.246.66.84:3000/etorbunova/tasks/" + task.id);
      if (task.title !== newTitle){
          axios.put("http://185.246.66.84:3000/etorbunova/tasks/" + task.id, {
              completed: task.completed,
              title: newTitle,
              sequence: task.sequence           
          })
          .then(response => {
              setTasks(prev =>{
                  return [...prev.filter(curr => curr.id !== task.id),response.data]
              });
          })
          .catch(error => console.log(error));
      }
      
  },[setTasks])   



  return (
    <>
      <div>
        <TaskForm tasksArr={tasks} showCompletedTasks={true} addButtonClick={CreateTask} deleteButtonClick={deleteTask} editButtonClick={renameTask} checkboxDone={checkboxDone}/>
      </div>
      <div>
        <TaskForm tasksArr={tasks} showCompletedTasks={false} addButtonClick={CreateTask}/>
      </div>
    </>
  );
}

export default App;






/*
    {
      "id": 1,
      "sequence": 1,
      "title": "Task 1",
      "completed": true
    },
    {
      "completed": false,
      "title": "Task 2",
      "id": 2,
      "sequence": 2
    },
    {
      "completed": false,
      "title": "Task 3",
      "id": 3,
      "sequence": 3
    }*/

// vue/todo/src/App.vue
<template>
  <div id="app">
    <h1>Todo list</h1>
    <TodoList 
      v-bind:todos="todos"
      @remove-todo="removeTodo"
      @check-todo="checkTodo"
      v-on:create-task="createTask"
    />
  </div>
</template>

<script>
import TodoList from '@/components/TodoList'
import axios from 'axios'

export default {
  name: 'App',
  
  data() {
    return {
      todos: [
      {id: 1, completed: false, title: 'Task 1', sequence: 1 },
      {id: 2, completed: false, title: 'Task 2', sequence: 2 },
      {id: 3, completed: false, title: 'Task 3', sequence: 3 },
      {id: 4, completed: false, title: 'Task 4', sequence: 4 },
      {id: 5, completed: false, title: 'Task 5', sequence: 5 },
      {id: 6, completed: true, title: 'Task 6', sequence: 6 }]
    }
  },
  mounted() {
    /*fetch("http://185.246.66.84:3000/etorbunova/tasks")
    .then(response => response.json())
    .then(json => {this.todos = json})*/
    axios.get("http://185.246.66.84:3000/etorbunova/tasks")
    .then(response => (this.todos = response.data));
  },


  components: {
    TodoList
  },
  methods: {
    removeTodo(id) {
      /*this.todos = this.todos.filter(t => t.id !== id)*/
      axios.delete("http://185.246.66.84:3000/etorbunova/tasks/" + id)
      .then(() => {this.todos = this.todos.filter(t => t.id !== id)})
    },
    createTask() {
      const newtodo = {
        completed: false,
        title: this.todos.length === 0 ? "Task 1" : "Task " + (this.todos.length + 1),
        sequence: 1
      }
      axios.post("http://185.246.66.84:3000/etorbunova/tasks", newtodo)
      .then(response => {this.todos = [...this.todos, response.data]})
    },
    checkTodo(id, ttitle, ssequence) {
      axios.put("http://185.246.66.84:3000/etorbunova/tasks/" + id, {
          completed: !this.todos.completed,
          title: ttitle,
          sequence: ssequence         
      })
      .then(response => { this.todos = [...this.todos.filter(t => t.id !== id),response.data];
      console.log(response.data)
      })
    }
  }
}

</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
